### ISSUE TITLE
all: API stability metaissue

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#570]
This is an issue to aggregate API stability issues from deprecated repos, culled by looking for the "API stability" milestone (and owner added).

Please add any you think are important or mark as completed those that are done.

[graph](https://github.com/gonum/graph/milestone/1):
- [x] https://github.com/gonum/graph/issues/87 @kortschak
- [x] https://github.com/gonum/graph/issues/46 @kortschak
- [x] https://github.com/gonum/graph/issues/18 @kortschak

[lapack](https://github.com/gonum/lapack/milestone/1):
- [x] https://github.com/gonum/lapack/issues/163 @vladimir-ch

[mat](https://github.com/gonum/matrix/milestone/1):
- [x] https://github.com/gonum/gonum/issues/756 @kortschak
- [x] https://github.com/gonum/gonum/issues/748 @btracey
- [x] https://github.com/gonum/gonum/issues/738 @btracey

**Comment by kortschak** [comment]
These are done.
